//=====================================================
// This file was auto-generated by xlate_vreg v1.1
//            -->  DO NOT EDIT!  <-- 
//=====================================================
#ifndef _FPGA_REG_H
#define _FPGA_REG_H


//
// Register:    RTL_MAJOR
// Size:        32-bits
// Description: "major" portion of RTL revision "major.minor.build"
//
#define RTL_MAJOR                                                    0x0000000000000000ULL


//
// Register:    RTL_MINOR
// Size:        32-bits
// Description: "minor" portion of RTL revision "major.minor.build"
//
#define RTL_MINOR                                                    0x0000000000000004ULL


//
// Register:    RTL_BUILD
// Size:        32-bits
// Description: "build" portion of RTL revision "major.minor.build"
//
#define RTL_BUILD                                                    0x0000000000000008ULL


//
// Register:    RTL_DATE
// Size:        32-bits
// Description: Build date
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     month                          8   31:24 RO   N/A         Build month (1 thru 12)
//     day                            8   23:16 RO   N/A         Build date  (1 thru 31)
//     year                           16  15:00 RO   N/A         Build year  (4 digit year)
//
#define RTL_DATE                                                     0x0000000000000010ULL
#define RTL_DATE_month                                               0x0818000000000010ULL
#define RTL_DATE_day                                                 0x0810000000000010ULL
#define RTL_DATE_year                                                0x1000000000000010ULL


//
// Register:    RTL_TYPE
// Size:        32-bits
// Description: Uniquely identifies this RTL design
//
#define RTL_TYPE                                                     0x0000000000000014ULL


//
// Register:    RTL_TIME
// Size:        32-bits
// Description: Build date
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     hour                           8   23:16 RO   N/A         Build month (0 thru 23)
//     min                            8   15:08 RO   N/A         Build date  (0 thru 59)
//     sec                            8   07:00 RO   N/A         Build year  (0 thru 59)
//
#define RTL_TIME                                                     0x000000000000001cULL
#define RTL_TIME_hour                                                0x081000000000001cULL
#define RTL_TIME_min                                                 0x080800000000001cULL
#define RTL_TIME_sec                                                 0x080000000000001cULL


//
// Register:    RTL_GIT_HASH
// Size:        This is an array of five consecutive 32-bit registers
// Description: Git commit hash
//
#define RTL_GIT_HASH                                                 0x0000000000000040ULL


//
// Register:    NIC0_STATUS
// Size:        32-bits
// Description: Hardware related status bits
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     link_stat                      1       0 RO   n/a         Ethernet link status
//     temp_ok                        1       1 RO   n/a         HBM RAM temperature OK
//
#define NIC0_STATUS                                                  0x0000000000001000ULL
#define NIC0_STATUS_link_stat                                        0x0100000000001000ULL
#define NIC0_STATUS_temp_ok                                          0x0101000000001000ULL


//
// Register:    NIC0_ERRORS
// Size:        32-bits
// Description: Error conditions
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pci_range_err                  1       0 RO   0           RDMX packet received with invalid target addr
//     overflow_0                     1       1 RO   0           Internal RAM buffer 0 overflow detected
//     overflow_1                     1       2 RO   0           Internal RAM buffer 1 overflow detected
//     seq_err                        1       3 RO   0           Sequence error.  Not normally used.
//                                                               In normal usage, this bit is often set and is not
//                                                               an error.
//
#define NIC0_ERRORS                                                  0x0000000000001004ULL
#define NIC0_ERRORS_pci_range_err                                    0x0100000000001004ULL
#define NIC0_ERRORS_overflow_0                                       0x0101000000001004ULL
#define NIC0_ERRORS_overflow_1                                       0x0102000000001004ULL
#define NIC0_ERRORS_seq_err                                          0x0103000000001004ULL


//
// Register:    NIC0_GOOD_PACKETS
// Size:        64-bits
// Description: Count of non-corrupt RDMX packets received
//              Will be cleared by writing a 1 to either NICx_RESET or NICx_CLEAR_COUNTERS
//
#define NIC0_GOOD_PACKETS                                            0x0000000000001008ULL


//
// Register:    NIC0_BAD_PACKETS
// Size:        64-bits
// Description: Count of corrupt RDMX packets received
//              Will be cleared by writing a 1 to either NICx_RESET or NICx_CLEAR_COUNTERS
//
#define NIC0_BAD_PACKETS                                             0x0000000000001010ULL


//
// Register:    NIC0_PCI_BASE
// Size:        64-bits
// Description: Base address in host RAM where received packets are stored
//
#define NIC0_PCI_BASE                                                0x0000000000001018ULL


//
// Register:    NIC0_PCI_SIZE
// Size:        64-bits
// Description: Size of the contiguous buffer in host RAM where received
//              packets are stored
//
#define NIC0_PCI_SIZE                                                0x0000000000001020ULL


//
// Register:    NIC0_RESET
// Size:        32-bits
// Description: System reset.  Writing a 1 will cause a system reset.  After writing
//              a 1, read this register until it auto-clears to 0.  Don't write a 1
//              to this register while packets are still being received
//
#define NIC0_RESET                                                   0x0000000000001028ULL


//
// Register:    NIC0_CLEAR_COUNTERS
// Size:        32-bits
// Description: Writing a 1 clears the NICx_GOOD_PACKETS and NICx_BAD_PACKETS
//              counter.  It is safe to clear the counters at any time.
//
#define NIC0_CLEAR_COUNTERS                                          0x000000000000102cULL


//
// Register:    NIC0_HBM_TEMP
// Size:        32-bits
// Description: HBM RAM temperature in whole degress Celsius
//
#define NIC0_HBM_TEMP                                                0x0000000000001030ULL


//
// Register:    NIC0_SENDER_PORT
// Size:        32-bits
// Description: Sender's QSFP port number
//
#define NIC0_SENDER_PORT                                             0x0000000000001034ULL


//
// Register:    NIC0_XMIT_SRCADDR
// Size:        64-bits
// Description: When transmitting a block of data, this is the source address in host-RAM
//
#define NIC0_XMIT_SRCADDR                                            0x0000000000001050ULL


//
// Register:    NIC0_XMIT_DSTADDR
// Size:        64-bits
// Description: When transmitting a block of data, this is the 64-bit RDMX target address
//
#define NIC0_XMIT_DSTADDR                                            0x0000000000001058ULL


//
// Register:    NIC0_XMIT_SIZE
// Size:        64-bits
// Description: When transmitting a block of data, this is the size of the data (in bytes)
//
#define NIC0_XMIT_SIZE                                               0x0000000000001060ULL


//
// Register:    NIC0_XMIT_START
// Size:        32-bits
// Description: Writing a 1 to this register begins transmission of a block of data.
//              This register will remain a '1' until the transmission is complete,
//              at which point it will auto-clear to 0.
//
#define NIC0_XMIT_START                                              0x0000000000001068ULL


//
// Register:    NIC0_PACKET_COUNT
// Size:        64-bits
// Description: Count of packets to generate.
//              ** For use by RTL engineers only **
//
#define NIC0_PACKET_COUNT                                            0x0000000000001080ULL


//
// Register:    NIC0_LOOPBACK
// Size:        32-bits
// Description: Set this to 1 to loop all incoming packets back to the source QSFP
//              ** For use by RTL engineers only **
//
#define NIC0_LOOPBACK                                                0x0000000000001088ULL


//
// Register:    NIC0_PAUSE_PCI
// Size:        32-bits
// Description: Write an integer to this register to "pause" PCI output for the
//              specified number of microseconds.
//              ** For use by RTL engineers only **
//
#define NIC0_PAUSE_PCI                                               0x000000000000108cULL


//
// Register:    NIC0_HWMARK_0
// Size:        64-bits
// Description: High-water mark for internal RAM bank 0
//              ** For use by RTL engineers only **
//
#define NIC0_HWMARK_0                                                0x0000000000001090ULL


//
// Register:    NIC0_HWMARK_1
// Size:        64-bits
// Description: High-water mark for internal RAM bank 1
//              ** For use by RTL engineers only **
//
#define NIC0_HWMARK_1                                                0x0000000000001098ULL


//
// Register:    NIC0_PCI_THROUGHPUT
// Size:        32-bits
// Description: The current write-throughput of the PCIe interface.
//              The units are data-cycles/second.  A data-cycle is 64 bytes.
//              ** For use by RTL engineers only **
//
#define NIC0_PCI_THROUGHPUT                                          0x00000000000010a0ULL


//
// Register:    NIC1_STATUS
// Size:        32-bits
// Description: Hardware related status bits
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     link_stat                      1       0 RO   n/a         Ethernet link status
//     temp_ok                        1       1 RO   n/a         HBM RAM temperature OK
//
#define NIC1_STATUS                                                  0x0000000000002000ULL
#define NIC1_STATUS_link_stat                                        0x0100000000002000ULL
#define NIC1_STATUS_temp_ok                                          0x0101000000002000ULL


//
// Register:    NIC1_ERRORS
// Size:        32-bits
// Description: Error conditions
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     pci_range_err                  1       0 RO   0           RDMX packet received with invalid target addr
//     overflow_0                     1       1 RO   0           Internal RAM buffer 0 overflow detected
//     overflow_1                     1       2 RO   0           Internal RAM buffer 1 overflow detected
//     seq_err                        1       3 RO   0           Sequence error.  Not normally used.
//                                                               In normal usage, this bit is often set and is not
//                                                               an error.
//
#define NIC1_ERRORS                                                  0x0000000000002004ULL
#define NIC1_ERRORS_pci_range_err                                    0x0100000000002004ULL
#define NIC1_ERRORS_overflow_0                                       0x0101000000002004ULL
#define NIC1_ERRORS_overflow_1                                       0x0102000000002004ULL
#define NIC1_ERRORS_seq_err                                          0x0103000000002004ULL


//
// Register:    NIC1_GOOD_PACKETS
// Size:        64-bits
// Description: Count of non-corrupt RDMX packets received
//              Will be cleared by writing a 1 to either NICx_RESET or NICx_CLEAR_COUNTERS
//
#define NIC1_GOOD_PACKETS                                            0x0000000000002008ULL


//
// Register:    NIC1_BAD_PACKETS
// Size:        64-bits
// Description: Count of corrupt RDMX packets received
//              Will be cleared by writing a 1 to either NICx_RESET or NICx_CLEAR_COUNTERS
//
#define NIC1_BAD_PACKETS                                             0x0000000000002010ULL


//
// Register:    NIC1_PCI_BASE
// Size:        64-bits
// Description: Base address in host RAM where received packets are stored
//
#define NIC1_PCI_BASE                                                0x0000000000002018ULL


//
// Register:    NIC1_PCI_SIZE
// Size:        64-bits
// Description: Size of the contiguous buffer in host RAM where received
//              packets are stored
//
#define NIC1_PCI_SIZE                                                0x0000000000002020ULL


//
// Register:    NIC1_RESET
// Size:        32-bits
// Description: System reset.  Writing a 1 will cause a system reset.  After writing
//              a 1, read this register until it auto-clears to 0.  Don't write a 1
//              to this register while packets are still being received
//
#define NIC1_RESET                                                   0x0000000000002028ULL


//
// Register:    NIC1_CLEAR_COUNTERS
// Size:        32-bits
// Description: Writing a 1 clears the NICx_GOOD_PACKETS and NICx_BAD_PACKETS
//              counter.  It is safe to clear the counters at any time.
//
#define NIC1_CLEAR_COUNTERS                                          0x000000000000202cULL


//
// Register:    NIC1_HBM_TEMP
// Size:        32-bits
// Description: HBM RAM temperature in whole degress Celsius
//
#define NIC1_HBM_TEMP                                                0x0000000000002030ULL


//
// Register:    NIC1_SENDER_PORT
// Size:        32-bits
// Description: Sender's QSFP port number
//
#define NIC1_SENDER_PORT                                             0x0000000000002034ULL


//
// Register:    NIC1_XMIT_SRCADDR
// Size:        64-bits
// Description: When transmitting a block of data, this is the source address in host-RAM
//
#define NIC1_XMIT_SRCADDR                                            0x0000000000002050ULL


//
// Register:    NIC1_XMIT_DSTADDR
// Size:        64-bits
// Description: When transmitting a block of data, this is the 64-bit RDMX target address
//
#define NIC1_XMIT_DSTADDR                                            0x0000000000002058ULL


//
// Register:    NIC1_XMIT_SIZE
// Size:        64-bits
// Description: When transmitting a block of data, this is the size of the data (in bytes)
//
#define NIC1_XMIT_SIZE                                               0x0000000000002060ULL


//
// Register:    NIC1_XMIT_START
// Size:        32-bits
// Description: Writing a 1 to this register begins transmission of a block of data.
//              This register will remain a '1' until the transmission is complete,
//              at which point it will auto-clear to 0.
//
#define NIC1_XMIT_START                                              0x0000000000002068ULL


//
// Register:    NIC1_PACKET_COUNT
// Size:        64-bits
// Description: Count of packets to generate.
//              ** For use by RTL engineers only **
//
#define NIC1_PACKET_COUNT                                            0x0000000000002080ULL


//
// Register:    NIC1_LOOPBACK
// Size:        32-bits
// Description: Set this to 1 to loop all incoming packets back to the source QSFP
//              ** For use by RTL engineers only **
//
#define NIC1_LOOPBACK                                                0x0000000000002088ULL


//
// Register:    NIC1_PAUSE_PCI
// Size:        32-bits
// Description: Write an integer to this register to "pause" PCI output for the
//              specified number of microseconds.
//              ** For use by RTL engineers only **
//
#define NIC1_PAUSE_PCI                                               0x000000000000208cULL


//
// Register:    NIC1_HWMARK_0
// Size:        64-bits
// Description: High-water mark for internal RAM bank 0
//              ** For use by RTL engineers only **
//
#define NIC1_HWMARK_0                                                0x0000000000002090ULL


//
// Register:    NIC1_HWMARK_1
// Size:        64-bits
// Description: High-water mark for internal RAM bank 1
//              ** For use by RTL engineers only **
//
#define NIC1_HWMARK_1                                                0x0000000000002098ULL


//
// Register:    NIC1_PCI_THROUGHPUT
// Size:        32-bits
// Description: The current write-throughput of the PCIe interface.
//              The units are data-cycles/second.  A data-cycle is 64 bytes.
//              ** For use by RTL engineers only **
//
#define NIC1_PCI_THROUGHPUT                                          0x00000000000020a0ULL



#endif
