connections = 
{
    /system_interconnect/axi_revision/S_AXI  src/common/axi_revision.v   RTL
    /channel_0/control/S_AXI                 src/control.v               NIC0 
    /channel_1/control/S_AXI                 src/control.v               NIC1  
}
